name: Generate App Icons

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-icons:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Generate launcher icons
        run: |
          flutter pub run flutter_launcher_icons

      - name: Commit and push icon assets
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(icons): generate app icons via CI"
            git push
          else
            echo "No icon changes to commit."
          fi